import type { Belt } from '@/domain/models/student';

export const BELT_RANKS: Record<Belt, number> = {
  'Branca': 1,
  // Infantis
  'Cinza e branca': 2,
  'Cinza': 3,
  'Cinza e preta': 4,
  'Amarela e branca': 5,
  'Amarela': 6,
  'Amarela e preta': 7,
  'Laranja e branca': 8,
  'Laranja': 9,
  'Laranja e preta': 10,
  'Verde e branca': 11,
  'Verde': 12,
  'Verde e preta': 13,
  // Adultos
  'Azul': 14,
  'Roxa': 15,
  'Marrom': 16,
  'Preta': 17,
  'Vermelha e preta': 18,
  'Vermelha e branca': 19,
  'Vermelha': 20
};

export const BAIRROS_DF = [
  'Água Quente',
  'Águas Claras',
  'Arapoanga',
  'Arniqueira',
  'Asa Norte',
  'Asa Sul',
  'Brazlândia',
  'Candangolândia',
  'Ceilândia',
  'Cruzeiro',
  'Fercal',
  'Gama',
  'Guará',
  'Itapoã',
  'Jardim Botânico',
  'Lago Norte',
  'Lago Sul',
  'Núcleo Bandeirante',
  'Paranoá',
  'Park Way',
  'Planaltina',
  'Plano Piloto',
  'Recanto das Emas',
  'Riacho Fundo I',
  'Riacho Fundo II',
  'Samambaia',
  'Santa Maria',
  'São Sebastião',
  'SCIA (Estrutural)',
  'SIA',
  'Sobradinho I',
  'Sobradinho II',
  'Sol Nascente/Pôr do Sol',
  'Sudoeste / Octogonal',
  'Taguatinga',
  'Varjão',
  'Vicente Pires'
];
