-- 00_esquema_inicial.sql
-- Define a estrutura das tabelas bases do sistema SFBJJ

-- 1. Tabela de Alunos
CREATE TABLE IF NOT EXISTS public.alunos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    cpf TEXT,
    "dataNascimento" TEXT,
    telefone TEXT,
    email TEXT,
    genero TEXT,
    "dataMatricula" TEXT,
    bairro TEXT,
    faixa TEXT NOT NULL,
    graus INTEGER NOT NULL DEFAULT 0,
    "dataUltimaGraduacao" TEXT,
    "contatoEmergenciaNome" TEXT,
    "contatoEmergenciaTel" TEXT,
    status TEXT NOT NULL DEFAULT 'Ativo',
    senha TEXT,
    turma TEXT NOT NULL DEFAULT 'Adulto',
    "fotoPerfil" TEXT,
    "modalidadePagamento" TEXT DEFAULT 'Mensal',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS para alunos
ALTER TABLE public.alunos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso total publico alunos" ON public.alunos FOR ALL USING (true);

-- 2. Tabela de Pagamentos
CREATE TABLE IF NOT EXISTS public.pagamentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "alunoId" bigint REFERENCES public.alunos(id) ON DELETE CASCADE,
    "mesRef" TEXT NOT NULL,
    valor NUMERIC NOT NULL DEFAULT 0.00,
    status TEXT NOT NULL DEFAULT 'Pendente',
    "dataVencimento" TEXT,
    "dataPagamento" TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS para pagamentos
ALTER TABLE public.pagamentos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso total publico pagamentos" ON public.pagamentos FOR ALL USING (true);

-- 3. Tabela de Aulas
CREATE TABLE IF NOT EXISTS public.aulas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hora TEXT NOT NULL,
    categoria TEXT NOT NULL,
    professor TEXT NOT NULL,
    "professorId" bigint, -- FK adicionada posteriormente em 05_ após criação de professores em 01_
    "turmaId" bigint,
    "diasSemana" INTEGER[] NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS para aulas
ALTER TABLE public.aulas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso total publico aulas" ON public.aulas FOR ALL USING (true);

-- 4. Tabela de Avisos
CREATE TABLE IF NOT EXISTS public.avisos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    conteudo TEXT NOT NULL,
    data TEXT NOT NULL,
    fixado BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS para avisos
ALTER TABLE public.avisos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso total publico avisos" ON public.avisos FOR ALL USING (true);
