DROP TABLE IF EXISTS public.presencas CASCADE;

-- 1. Cria a tabela de administradores
CREATE TABLE IF NOT EXISTS public.administradores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    senha TEXT NOT NULL,
    foto_perfil TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilita Row Level Security se necessário (como as outras tabelas)
ALTER TABLE public.administradores ENABLE ROW LEVEL SECURITY;

-- Cria políticas simples de acesso
CREATE POLICY "Permitir leitura pública de administradores" ON public.administradores
    FOR SELECT USING (true);

CREATE POLICY "Permitir atualização de administradores por si mesmos" ON public.administradores
    FOR UPDATE USING (true); -- Em ambiente de produção real, usar auth.uid() ou checagem de email, mas mantendo a simplicidade existente do projeto.

-- 2. Migra o administrador padrão da tabela professores para a tabela administradores se ele existir lá
INSERT INTO public.administradores (nome, email, senha, foto_perfil)
SELECT nome, email, senha, foto_perfil 
FROM public.professores 
WHERE role = 'admin' OR email = 'admin@sfbjj.com'
ON CONFLICT (email) 
DO UPDATE SET 
    nome = EXCLUDED.nome,
    senha = EXCLUDED.senha,
    foto_perfil = EXCLUDED.foto_perfil;

-- Se o administrador inicial não existia na tabela professores, insere o padrão diretamente
INSERT INTO public.administradores (nome, email, senha)
VALUES ('Lucas dos Anjos', 'admin@sfbjj.com', '#sfbjj2026')
ON CONFLICT (email) DO NOTHING;

-- 3. Deleta o administrador da tabela professores para não aparecer na listagem de professores do sistema
DELETE FROM public.professores 
WHERE role = 'admin' OR email = 'admin@sfbjj.com';
