-- 08_cria_tabela_turmas.sql
-- Cria a tabela de turmas e define a chave estrangeira em aulas se não existir

CREATE TABLE IF NOT EXISTS public.turmas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    categoria TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS para turmas
ALTER TABLE public.turmas ENABLE ROW LEVEL SECURITY;

-- Remover políticas existentes se houver, e criar nova
DROP POLICY IF EXISTS "Acesso total publico turmas" ON public.turmas;
CREATE POLICY "Acesso total publico turmas" ON public.turmas FOR ALL USING (true);

-- Vincular a coluna turmaId de aulas com a tabela turmas de forma íntegra
UPDATE public.aulas 
SET "turmaId" = NULL 
WHERE "turmaId" IS NOT NULL 
  AND "turmaId" NOT IN (SELECT id FROM public.turmas);

ALTER TABLE public.aulas
    DROP CONSTRAINT IF EXISTS fk_aulas_turma,
    ADD CONSTRAINT fk_aulas_turma FOREIGN KEY ("turmaId") REFERENCES public.turmas(id) ON DELETE SET NULL;
