-- 09_controle_frequencia.sql
-- Cria a tabela de frequências/check-ins dos alunos

CREATE TABLE IF NOT EXISTS public.frequencias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id bigint NOT NULL REFERENCES public.alunos(id) ON DELETE CASCADE,
    aula_id bigint NOT NULL REFERENCES public.aulas(id) ON DELETE CASCADE,
    turma_id bigint REFERENCES public.turmas(id) ON DELETE SET NULL,
    data DATE NOT NULL DEFAULT CURRENT_DATE,
    horario TIME NOT NULL DEFAULT CURRENT_TIME,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT uniq_aluno_aula_data UNIQUE (aluno_id, aula_id, data)
);

-- Habilitar RLS para frequencias
ALTER TABLE public.frequencias ENABLE ROW LEVEL SECURITY;

-- Criar política de acesso público total
DROP POLICY IF EXISTS "Acesso total publico frequencias" ON public.frequencias;
CREATE POLICY "Acesso total publico frequencias" ON public.frequencias FOR ALL USING (true);
