-- 10_curriculo_e_rls.sql
-- Migração para criação da tabela de técnicas e auditoria de políticas de segurança RLS

-- 1. Criação da tabela de técnicas (currículo da semana)
CREATE TABLE IF NOT EXISTS public.tecnicas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo text NOT NULL,
    descricao text NOT NULL,
    categoria text NOT NULL, -- 'Kids' | 'Adulto' | 'Geral'
    classificacao text NOT NULL DEFAULT 'Outros', -- 'Guarda' | 'Passagem' | 'Raspagem' | 'Finalização' | 'Queda' | 'Defesa' | 'Outros'
    video_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitação do Row Level Security (RLS) nas técnicas
ALTER TABLE public.tecnicas ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de acesso para a tabela de técnicas
DROP POLICY IF EXISTS "Acesso leitura publico tecnicas" ON public.tecnicas;
CREATE POLICY "Acesso leitura publico tecnicas" ON public.tecnicas
    FOR SELECT USING (true);

-- Como a aplicação acessa via chave anônima (sem login nativo no Supabase Auth),
-- as políticas de escrita devem permitir acesso público no ambiente de desenvolvimento local.
DROP POLICY IF EXISTS "Acesso total publico tecnicas" ON public.tecnicas;
CREATE POLICY "Acesso total publico tecnicas" ON public.tecnicas
    FOR ALL USING (true);

DROP POLICY IF EXISTS "Professores e Admins gerenciam tecnicas" ON public.tecnicas;
-- Comentada temporariamente para compatibilidade com autenticação anônima (sem Supabase Auth):
-- CREATE POLICY "Professores e Admins gerenciam tecnicas" ON public.tecnicas
--     FOR ALL USING (
--         (auth.jwt() ->> 'email') IN (SELECT email FROM public.professores)
--     );

-- 4. Auditoria de RLS: Refinamento de políticas na tabela de ALUNOS
ALTER TABLE public.alunos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Alunos leem seus proprios dados" ON public.alunos;
DROP POLICY IF EXISTS "Professores e Admins gerenciam alunos" ON public.alunos;
DROP POLICY IF EXISTS "Acesso total publico alunos" ON public.alunos;

-- Reestabelece acesso público para permitir o funcionamento anônimo
CREATE POLICY "Acesso total publico alunos" ON public.alunos FOR ALL USING (true);

-- Políticas de produção recomendadas (ativar ao integrar com o Supabase Auth):
-- CREATE POLICY "Alunos leem seus proprios dados" ON public.alunos
--     FOR SELECT USING (
--         (auth.jwt() ->> 'email' = email) OR 
--         ((auth.jwt() ->> 'email') IN (SELECT email FROM public.professores))
--     );
-- CREATE POLICY "Professores e Admins gerenciam alunos" ON public.alunos
--     FOR ALL USING (
--         (auth.jwt() ->> 'email') IN (SELECT email FROM public.professores)
--     );

-- 5. Auditoria de RLS: Refinamento de políticas na tabela de PAGAMENTOS
ALTER TABLE public.pagamentos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Alunos leem seus proprios pagamentos" ON public.pagamentos;
DROP POLICY IF EXISTS "Admins gerenciam pagamentos" ON public.pagamentos;
DROP POLICY IF EXISTS "Acesso total publico pagamentos" ON public.pagamentos;

-- Reestabelece acesso público para permitir o funcionamento anônimo
CREATE POLICY "Acesso total publico pagamentos" ON public.pagamentos FOR ALL USING (true);

-- Políticas de produção recomendadas (ativar ao integrar com o Supabase Auth):
-- CREATE POLICY "Alunos leem seus proprios pagamentos" ON public.pagamentos
--     FOR SELECT USING (
--         ((SELECT email FROM public.alunos WHERE id = "alunoId") = auth.jwt() ->> 'email') OR
--         ((auth.jwt() ->> 'email') IN (SELECT email FROM public.professores))
--     );
-- CREATE POLICY "Admins gerenciam pagamentos" ON public.pagamentos
--     FOR ALL USING (
--         (SELECT role FROM public.professores WHERE email = auth.jwt() ->> 'email') = 'admin'
--     );

-- 6. Auditoria de RLS: Refinamento de políticas na tabela de FREQUENCIAS
ALTER TABLE public.frequencias ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Alunos leem suas proprias frequencias" ON public.frequencias;
DROP POLICY IF EXISTS "Professores e Admins gerenciam frequencias" ON public.frequencias;
DROP POLICY IF EXISTS "Acesso total publico frequencias" ON public.frequencias;

-- Reestabelece acesso público para permitir o funcionamento anônimo
CREATE POLICY "Acesso total publico frequencias" ON public.frequencias FOR ALL USING (true);

-- Políticas de produção recomendadas (ativar ao integrar com o Supabase Auth):
-- CREATE POLICY "Alunos leem suas proprias frequencias" ON public.frequencias
--     FOR SELECT USING (
--         ((SELECT email FROM public.alunos WHERE id = aluno_id) = auth.jwt() ->> 'email') OR
--         ((auth.jwt() ->> 'email') IN (SELECT email FROM public.professores))
--     );
-- CREATE POLICY "Professores e Admins gerenciam frequencias" ON public.frequencias
--     FOR ALL USING (
--         (auth.jwt() ->> 'email') IN (SELECT email FROM public.professores)
--     );
