-- Migração: Tabela de Logs de Envio de E-mail para Auditoria
CREATE TABLE IF NOT EXISTS public.logs_envio_email (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id BIGINT REFERENCES public.alunos(id) ON DELETE SET NULL,
    email_destino TEXT NOT NULL,
    nome_usuario TEXT,
    assunto TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Sucesso', 'Falha')),
    erro TEXT,
    enviado_por TEXT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para otimização de consultas e auditoria
CREATE INDEX IF NOT EXISTS idx_logs_envio_email_aluno_id ON public.logs_envio_email(aluno_id);
CREATE INDEX IF NOT EXISTS idx_logs_envio_email_status ON public.logs_envio_email(status);
CREATE INDEX IF NOT EXISTS idx_logs_envio_email_criado_em ON public.logs_envio_email(criado_em DESC);

-- Habilitar RLS (Row Level Security) na tabela
ALTER TABLE public.logs_envio_email ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS para administradores e professores
CREATE POLICY "Permitir leitura de logs de email para usuários autenticados"
    ON public.logs_envio_email
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Permitir inserção de logs de email para anon e authenticated"
    ON public.logs_envio_email
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);
