-- 17_validacao_tecnicas_e_notificacoes.sql
-- Migração para suporte a validação de posições sugeridas por alunos e sistema de notificações in-app

-- 1. Garante que a coluna 'classificacao' existe na tabela 'tecnicas'
ALTER TABLE public.tecnicas 
  ADD COLUMN IF NOT EXISTS classificacao text NOT NULL DEFAULT 'Outros',
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'aprovado',
  ADD COLUMN IF NOT EXISTS aluno_id bigint REFERENCES public.alunos(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS aluno_nome text,
  ADD COLUMN IF NOT EXISTS feedback_admin text,
  ADD COLUMN IF NOT EXISTS validado_por text,
  ADD COLUMN IF NOT EXISTS validado_em timestamp with time zone;

-- Índices para otimização de busca por status e aluno
CREATE INDEX IF NOT EXISTS idx_tecnicas_status ON public.tecnicas(status);
CREATE INDEX IF NOT EXISTS idx_tecnicas_aluno_id ON public.tecnicas(aluno_id);

-- 2. Criar tabela de notificações in-app dos alunos
CREATE TABLE IF NOT EXISTS public.notificacoes ( 
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id bigint NOT NULL REFERENCES public.alunos(id) ON DELETE CASCADE,
    titulo text NOT NULL,
    mensagem text NOT NULL,
    tipo text NOT NULL DEFAULT 'info', -- 'posicao_aprovada' | 'posicao_rejeitada' | 'info'
    lida boolean NOT NULL DEFAULT false,
    tecnica_id bigint REFERENCES public.tecnicas(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS na tabela de notificações
ALTER TABLE public.notificacoes ENABLE ROW LEVEL SECURITY;

-- Política RLS pública para ambiente sem Supabase Auth nativo
DROP POLICY IF EXISTS "Acesso total publico notificacoes" ON public.notificacoes;
CREATE POLICY "Acesso total publico notificacoes" ON public.notificacoes FOR ALL USING (true);
