-- 18_modulo_graduacoes_audit_e_elegibilidade.sql
-- Adiciona tabela de auditoria imutável, suporte a exclusão lógica e campos de validação de certificado de graduação

-- 1. Tabela de logs de auditoria
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidade TEXT NOT NULL,
    entidade_id INTEGER NOT NULL,
    acao TEXT NOT NULL, -- 'INSERT', 'UPDATE', 'DELETE', 'PROMOTE'
    usuario TEXT NOT NULL,
    ip TEXT,
    valores_anteriores JSONB,
    valores_novos JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso total publico audit_logs" ON public.audit_logs FOR ALL USING (true);

-- 2. Adicionar colunas extras e exclusão lógica em graduacoes_historico
ALTER TABLE public.graduacoes_historico ADD COLUMN IF NOT EXISTS observacoes TEXT;
ALTER TABLE public.graduacoes_historico ADD COLUMN IF NOT EXISTS usuario_lancamento TEXT;
ALTER TABLE public.graduacoes_historico ADD COLUMN IF NOT EXISTS codigo_validacao_qr TEXT;
ALTER TABLE public.graduacoes_historico ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.graduacoes_historico ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT false NOT NULL;

-- 3. Índices de alta performance para evitar N+1 e acelerar consultas de histórico
CREATE INDEX IF NOT EXISTS idx_graduacoes_historico_aluno_id ON public.graduacoes_historico(aluno_id);
CREATE INDEX IF NOT EXISTS idx_graduacoes_historico_is_deleted ON public.graduacoes_historico(is_deleted);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entidade_id ON public.audit_logs(entidade, entidade_id);
