name: Deploy SFBJJ

on:
  push:
    branches:
      - feat/ias-hostgator

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Gerar build
        run: npm run build

      - name: Publicar na HostGator
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.45954aab77704702afe51744375733133.domain-placeholder.temp
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./dist/
          server-dir: sfbjj/